steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/winged-carrier-299322/gcp-stub:2.0', '-f', './backend/gcp-stub/gcp-stub/Dockerfile', '.' ]
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/winged-carrier-299322/gcp-stub:2.0']
