steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '--no-cache', '-t', 'gcr.io/winged-carrier-299322/stub:$SHORT_SHA', '-f', './backend/gcp-stub/gcp-stub/Dockerfile', '.' ]
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/winged-carrier-299322/stub:$SHORT_SHA']
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '--no-cache', '-t', 'gcr.io/winged-carrier-299322/api:$SHORT_SHA', '-f', './backend/gcp-api/gcp-api/Dockerfile', '.' ]
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/winged-carrier-299322/api:$SHORT_SHA']
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '--no-cache', '-t', 'gcr.io/winged-carrier-299322/ui:$SHORT_SHA', '-f', './ui/gcp-ui/Dockerfile', '.' ]
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/winged-carrier-299322/ui:$SHORT_SHA']

  # [START cloudbuild-trigger-cd]
# This step clones the deployment-env repository
- name: 'gcr.io/cloud-builders/gcloud'
  id: Clone env repository
  entrypoint: /bin/sh
  args:
  - '-c'
  - |
    gcloud source repos clone deployment-env && \
    cd deployment-env && \
    git checkout candidate && \
    git config user.email $(gcloud auth list --filter=status:ACTIVE --format='value(account)')

# This step generates the new manifest
- name: 'gcr.io/cloud-builders/gcloud'
  id: Generate manifest
  entrypoint: /bin/sh
  args:
  - '-c'
  - |
     sed "s/GOOGLE_CLOUD_PROJECT/${PROJECT_ID}/g" pod.tpl | \
     sed "s/COMMIT_SHA/${SHORT_SHA}/g" > deployment-env/kubernetes.yaml

# This step pushes the manifest back to deployment-env
- name: 'gcr.io/cloud-builders/gcloud'
  id: Push manifest
  entrypoint: /bin/sh
  args:
  - '-c'
  - |
    set -x && \
    cd deployment-env && \
    git add kubernetes.yaml && \
    git commit -m "Deploying image gcr.io/${PROJECT_ID}/deployment-env:${SHORT_SHA}
    Built from commit ${COMMIT_SHA} of repository deployment-env-app
    Author: $(git log --format='%an <%ae>' -n 1 HEAD)" && \
    git push origin candidate

# [END cloudbuild-trigger-cd]


