apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: api-ingress
  namespace: gcp-deployment
  annotations:  
    konghq.com/strip-path: "true"
    kubernetes.io/ingress.class: kong
    konghq.com/plugins: kong-header-demo
spec:
  tls:
  - hosts:
#      - k8s.eccordion.com
      - localhost
    secretName: api-tls
  rules:
  - http:
      paths:
      - path: /services/api
        pathType: Prefix
        backend:
          serviceName: gcp-api
          servicePort: 80
      - path: /services/api
        pathType: Prefix
        backend:
          serviceName: gcp-api
          servicePort: 443        
      - path: /
        pathType: Prefix
        backend:
          serviceName: gcp-ui
          servicePort: 80        
      - path: /
        pathType: Prefix
        backend:
          serviceName: gcp-ui
          servicePort: 443