apiVersion: v1
kind: Service
metadata:
  labels:
    app: gcp
  name: gcp-api
  namespace: gcp-deployment
spec:
  ports:
  - port: 443
    name: high
    protocol: TCP
    targetPort: 5001
  selector:
    app: gcp
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: gcp
  name: gcp-ui
  namespace: gcp-deployment
spec:
  ports:
  - port: 443
    name: high
    protocol: TCP
    targetPort: 443
  selector:
    app: gcp    